version: "3.4"
services:

  py-service:
    build: py
    command: python app.py
    ports:
      - 80:5000
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - 16686:16686
      - "6831:6831/udp"
